name: Create PR on Push 
on:
  push:
    branches:
      - 'main_sec'

jobs:
  create-pr:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Append text to version.txt
        run: |
          cd $env:GITHUB_WORKSPACE
          echo "Appended text at $(date)" >> Version.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERS_TOKEN }}
        run: |
          git config user.name "Agent 007"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Update version.txt via GitHub Actions"
          git push origin HEAD:${GITHUB_REF_NAME}
          ./test.ps1

      
