name: Create PR on Push 
on:
  push:
    branches:
      - 'main_sec'

jobs:
  create-pr:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Append text to version.txt
        run: |
          cd $env:GITHUB_WORKSPACE
          echo "Appended text at $(date)" >> Version.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERS_TOKEN }}
        run: |
          git config user.name "Agent 007"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Update version.txt via GitHub Actions"
          git push origin HEAD:${GITHUB_REF_NAME}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERS_TOKEN }}
        run: |
          $env:GH_TOKEN = $env:GITHUB_TOKEN
          $repo = "Marian042/Test_PR"
          $sourceBranch = "main_sec"
          $baseBranch = "main"
          git checkout $sourceBranch
          git push origin $sourceBranch
          $prTitle = "Auto PR GitHub Actions"
          $prBody = "This pull request was automatically created from branch $sourceBranch to $baseBranch."
          gh pr create `
          --title "$prTitle" `
          --body "$prBody" `
          --base "$baseBranch" `
          --head "$sourceBranch" `
          --repo "$repo"
      
