name: Create PR on Push 
on:
  push:
    branches:
      - 'main_sec'

jobs:
  create-pr:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: PR
        env:
          GITHUB_TOKEN: ${{ secrets.PERS_TOKEN }}
        run: |
          $env:GH_TOKEN = $env:GITHUB_TOKEN
          $repo = "Marian042/Test_PR"
          $sourceBranch = "main_sec"
          $baseBranch = "main"
          $lab = "bug"
          git checkout $sourceBranch
          git push origin $sourceBranch
          $prTitle = "Auto PR GitHub Actions"
          $prBody = "This pull request was automatically created from branch $sourceBranch to $baseBranch."
          gh pr create `
          --title "$prTitle" `
          --body "$prBody" `
          --label "%lab" ` 
          --base "$baseBranch" `
          --head "$sourceBranch" `
          --repo "$repo"
      
