name: Create PR on Push 
on:
  push:
    branches:
      - 'main_sec'

jobs:
  create-pr:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write current time to version.txt (PowerShell)
        shell: powershell
        run: |
          $time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          Set-Content -Path "Version.txt" -Value "Current time: $time"

      - name: Commit and push changes
        shell: cmd
        env:
          MY_TOKEN: ${{ secrets.PERS_TOKEN }}
        run: |
          cd /d %GITHUB_WORKSPACE%
          git config --global user.name "Agent 007"
          git config --global user.email "agent007@example.com"
          git add Version.txt 
          git commit -m "Update version.txt via GitHub Actions" 
          git remote set-url origin https://%MY_TOKEN%@github.com/Marian042/Test_PR.git
          git push 

      - name: PR
        env:
          GITHUB_TOKEN: ${{ secrets.PERS_TOKEN }}
        run: |
          $env:GH_TOKEN = $env:GITHUB_TOKEN
          $repo = "Marian042/Test_PR"
          $sourceBranch = "main_sec"
          $baseBranch = "main"
          git checkout $sourceBranch
          git push origin $sourceBranch
          $prTitle = "Auto PR GitHub Actions"
          $prBody = "This pull request was automatically created from branch $sourceBranch to $baseBranch."
          gh pr create `
          --title "$prTitle" `
          --body "$prBody" `
          --base "$baseBranch" `
          --head "$sourceBranch" `
          --repo "$repo"
      
